"""1206 F2 — the Python SDK speaks the canonical v2 request.

Anchored on ``coderifts-app/test/fixtures/v2-grant-canonical-request.json``: the request AND the
normalized reading the app handler produces from it.

Byte-equivalence alone is not parity. ``state_nonce`` is sent under that name and read as
``nonce``; an absent ``expected_state_token`` is ``''`` and not unbound. A fixture that only
carried the request would let every speaker agree on the bytes and still bind different grants.

NON-SILENT SKIP: without the app checkout this SKIPS with a named reason. A green suite that
proved nothing about parity is the failure this file exists to prevent.
"""

import json
import os
import pathlib

import pytest

from coderifts.types import EXECUTION_GRANT_V2_REQUEST_FIELDS


def _fixture_path():
    roots = [
        os.environ.get("CODERIFTS_APP_ROOT"),
        os.path.join(os.path.expanduser("~"), "coderifts-app"),
        str(pathlib.Path(__file__).resolve().parents[2] / "coderifts-app"),
    ]
    for root in roots:
        if not root:
            continue
        p = pathlib.Path(root) / "test" / "fixtures" / "v2-grant-canonical-request.json"
        if p.exists():
            return p
    return None


FIXTURE_PATH = _fixture_path()
pytestmark = pytest.mark.skipif(
    FIXTURE_PATH is None,
    reason=(
        "coderifts-app checkout not found — set CODERIFTS_APP_ROOT. "
        "Request parity is UNPROVEN here, not proven-by-absence."
    ),
)


@pytest.fixture(scope="module")
def fixture():
    return json.loads(FIXTURE_PATH.read_text())


def test_fixture_is_the_generated_one(fixture):
    assert fixture["schema"] == "coderifts.v2-grant-canonical-request.v1"
    assert "GENERATED by scripts/generate-grant-request-types.js" in fixture["$comment"]


def test_every_declared_field_is_in_the_canonical_request(fixture):
    request = fixture["request"]
    for field in EXECUTION_GRANT_V2_REQUEST_FIELDS:
        assert field in request, (
            f"the Python SDK declares {field} but the canonical request does not"
        )


def test_byte_equivalence_on_the_declared_wire_fields(fixture):
    request = fixture["request"]
    body = {f: request[f] for f in EXECUTION_GRANT_V2_REQUEST_FIELDS if f in request}
    for key, value in body.items():
        assert json.dumps(value, sort_keys=True) == json.dumps(
            request[key], sort_keys=True
        ), f"{key} does not serialise byte-equivalently to the canonical request"


def test_agreement_with_the_reading_including_the_rename(fixture):
    request, reading = fixture["request"], fixture["reading"]
    # The half byte-equivalence cannot cover.
    assert request["state_nonce"] == reading["nonce"], "sent as state_nonce, read as nonce"
    assert request["expected_state_token"] == reading["expected_state_token"]
    assert request["context"]["operation"] == reading["operation"]
    assert request["tenant_id"] == reading["tenant_id"]
    assert request["target_uri"] == reading["target_uri"]


def test_audience_hash_is_derived_not_sent(fixture):
    # The Python SDK names it as minted rather than a request param — and the reading agrees.
    assert "audience_hash" not in fixture["reading"]
    assert "NOT in the reading" in fixture["reading_notes"]["audience_hash"]


def test_policy_hash_is_now_a_read_field(fixture):
    # 1206 variant A: the server forwards and binds it. A speaker that still calls it
    # minted-only is stale, and this is where that shows up.
    assert fixture["reading"]["policy_hash"] == fixture["request"]["policy_hash"]
